<?php

namespace App\Http\Controllers\BackEnd;

class GlobalActionController extends Controller
{
    // CONVERT FROM ACTIONS TO MODEL

    protected $actionsToModel = [
        // GET MASTER
        'getUser' => 'User',
        'getBranch' => 'Branch',
        'getCountry' => 'Country',
        'getCurrency' => 'Currency',
        'getCity' => 'Port',
        'getCompany' => 'Company',
        'getContainerSize' => 'ContainerSize',
        'getContainerType' => 'ContainerType',
        'getDistrict' => 'District',
        'getEmployee' => 'Employee',
        'getEmployeeDisease' => 'EmployeeDisease',
        'getMeasurementUnit' => 'MeasurementUnit',
        'getMenu' => 'Menu',
        'getNote' => 'Note',
        'getPort' => 'Port',
        'getPrincipal' => 'Principal',
        'getPrincipalBankAccount' => 'PrincipalBankAccount',
        'getPrincipalBlacklist' => 'PrincipalBlacklist',
        'getPrincipalCommodity' => 'PrincipalCommodity',
        'getPrincipalGroup' => 'PrincipalGroup',
        'getService' => 'Service',
        'getServiceGroup' => 'ServiceGroup',
        'getServicePrice' => 'ServicePrice',
        'getServiceTag' => 'ServiceTag',
        'getServiceTerm' => 'ServiceTerm',
        'getSetting' => 'Setting',
        'getUserGroup' => 'UserGroup',
        'getCarrier' => 'Carrier',
        'getServiceBudget' => 'ServiceBudget',
        'getBc' => 'Bc',
        'getContainer' => 'Container',
        'getDeliveryStatus' => 'DeliveryStatus',
        'getTaxInvoice' => 'TaxInvoice',
        'getCommodityCategory' => 'CommodityCategory',
        'getLogo' => 'Logo',
        'getNationalHoliday' => 'NationalHoliday',
        'getPaymentMethod' => 'PaymentMethod',
        'getOriginalCopy' => 'OriginalCopy',
        'getPaymentTerm' => 'PaymentTerm',
        'getPortInterchange' => 'PortInterchange',
        'getPrincipalCategory' => 'PrincipalCategory',
        'getPrincipalTitle' => 'PrincipalTitle',
        'getRemark' => 'Remark',
        'getReminder' => 'Reminder',
        'getServiceCategory' => 'ServiceCategory',
        'getDocumentSetting' => 'DocumentSetting',
        'getDocumentDistribution' => 'DocumentDistribution',
        'getWebsite' => 'Website',
        'getUserTeam' => 'UserTeam',
        'getUserTeamDetail' => 'UserTeamDetail',
        'getBankAccount' => 'BankAccount',
        'getTaxInvoiceDetail' => 'TaxInvoiceDetail',
        'getTaxInvoiceVoid' => 'TaxInvoiceVoid',
        'getNoteTemplate' => 'NoteTemplate',
        'getPrincipalAddress' => 'PrincipalAddress',
        'getPrincipalCategoryDetail' => 'PrincipalCategoryDetail',
        'getPrincipalPic' => 'PrincipalPic',
        'getContainerAgency' => 'ContainerAgency',
        'getAccessMenu' => 'AccessMenu',
        'getNotification' => 'Notification',

        //GET PRE BOOKING
        'getLockedParty' => 'Principal',

        // GET PREORDER
        'getPreOrder' => 'PreOrder',
        // GET PREORDER GRID / DETAIL
        'getDetailPartyGrid' => 'PreOrderParty',
        'getDetailPackingGrid' => 'PosPackingDetail',
        'getDetailItemShipmentGrid' => 'PosShipmentItem',
        'getDetailContainerGrid' => 'PreOrderContainer',

        // GET GRID Detail        
        'getUserBranchGrid' => 'Branch',
        'getUserCompanyGrid' => 'Company',
        'getUserGroupUserGrid' => 'UserGroup',

        'getBranchAccessGrid' => 'AccessMaster',
        'getWebsiteAccessGrid' => 'AccessMaster',
        'getBranchReportAccessGrid' => 'AccessMaster',
        'getPrincipalFileAccessGrid' => 'AccessMaster',
        'getPrincipalGroupFileAccessGrid' => 'AccessMaster',
        'getPrincipalGroupAccessGrid' => 'AccessMaster',
        'getDocumentDistributionAccessGrid' => 'AccessMaster',

        'getPrincipalCommodityGrid' => 'PrincipalCommodity',
        'getUserTeamUserGrid' => 'User',
        'getPrincipalPicGrid' => 'PrincipalPic',
        'getPrincipalCategoryGrid' => 'PrincipalCategory',
        'getServiceFromSupplierGrid' => 'ServiceFromSupplier',
        'getPrincipalAddressGrid' => 'PrincipalAddress',
        'getRfqCargoGrid' => 'RfqCargo',
        'getRfqServiceBuyGrid' => 'RfqDetail',
        'getRfqServiceSellGrid' => 'RfqDetail',
        'getRfqNoteGrid' => 'Rfq',

        // Grid detail principal group
        'getPrincipalGrid' => 'Principal',


        // GET ENUM
        'getEnumPrincipalTitleData' => 'principals_title',
        'getEnumPrincipalRoleData' => 'principals_role',
        'getEnumServiceTagCategoryData' => 'service_tags_category',
        'getEnumContainerTypeCategoryData' => 'container_types_category',
        'getEnumNoteCategoryData' => 'notes_category',
        'getEnumServiceTermCategoryData' => 'service_terms_category',
        'getEnumUserGroupCategoryData' => 'user_groups_category',
        'getEnumRfqTradeData' => 'rfqs_trade',
        'getEnumRfqShippindModeData' => 'rfqs_shipping_mode',
        'getEnumRfqTypeOfShipmentData' => 'rfqs_type_of_shipment',
        'getEnumRfqDetailOrderTypeData' => 'rfq_details_order_type',
        'getEnumBcsOrderTypeData' => 'bcs_order_type',
        'getEnumUserTeamOnhandStatusData' => 'user_teams_onhand_status',
        'getQuotation' => 'Rfq',
        'getTeamWork' => 'TeamWork',

        // GET FILE
        'getPrincipalDataFile' => 'File',

        // ADD MASTER
        'addUser' => 'User',
        'addBranch' => 'Branch',
        'addCountry' => 'Country',
        'addCurrency' => 'Currency',
        'addCity' => 'Port',
        'addCompany' => 'Company',
        'addContainerSize' => 'ContainerSize',
        'addContainerType' => 'ContainerType',
        'addDistrict' => 'District',
        'addEmployee' => 'Employee',
        'addEmployeeDisease' => 'EmployeeDisease',
        'addMeasurementUnit' => 'MeasurementUnit',
        'addMenu' => 'Menu',
        'addNote' => 'Note',
        'addPort' => 'Port',
        'addPrincipal' => 'Principal',
        'addPrincipale' => 'Principal',
        'addPrincipalBankAccount' => 'PrincipalBankAccount',
        'addPrincipalBlacklist' => 'PrincipalBlacklist',
        'addPrincipalCommodity' => 'PrincipalCommodity',
        'addPrincipalGroup' => 'PrincipalGroup',
        'addService' => 'Service',
        'addServiceGroup' => 'ServiceGroup',
        'addServicePrice' => 'ServicePrice',
        'addServiceTag' => 'ServiceTag',
        'addServiceTerm' => 'ServiceTerm',
        'addSetting' => 'Setting',
        'addUserGroup' => 'UserGroup',
        'addCarrier' => 'Carrier',
        'addServiceBudget' => 'ServiceBudget',
        'addBc' => 'Bc',
        'addContainer' => 'Container',
        'addDeliveryStatus' => 'DeliveryStatus',
        'addTaxInvoice' => 'TaxInvoice',
        'addTaxInvoiceDetail' => 'TaxInvoiceDetail',
        'addTaxInvoiceVoid' => 'TaxInvoiceVoid',
        'addLogo' => 'Logo',
        'addNationalHoliday' => 'NationalHoliday',
        'addPaymentMethod' => 'PaymentMethod',
        'addOriginalCopy' => 'OriginalCopy',
        'addPaymentTerm' => 'PaymentTerm',
        'addPortInterchange' => 'PortInterchange',
        'addPrincipalCategory' => 'PrincipalCategory',
        'addPrincipalTitle' => 'PrincipalTitle',
        'addRemark' => 'Remark',
        'addReminder' => 'Reminder',
        'addCommodityCategory' => 'CommodityCategory',
        'addServiceCategory' => 'ServiceCategory',
        'addDocumentSetting' => 'DocumentSetting',
        'addDocumentDistribution' => 'DocumentDistribution',
        'addWebsite' => 'Website',
        'addUserTeam' => 'UserTeam',
        'addUserTeamDetail' => 'UserTeamDetail',
        'addBankAccount' => 'BankAccount',
        'addNoteTemplate' => 'NoteTemplate',
        'addPrincipalAddress' => 'PrincipalAddress',
        'addPrincipalCategoryDetail' => 'PrincipalCategoryDetail',
        'addPrincipalPic' => 'PrincipalPic',
        'addContainerAgency' => 'ContainerAgency',
        'addCommodityCategory' => 'CommodityCategory',

        // ADD PRE BOOKING
        'addLockedParty' => 'PrincipalBlacklist',
        'addQuotation' => 'Rfq',
        'addTeamWork' => 'TeamWork',
        'addRfqCargo' => 'RfqCargo',
        'addRfqServiceBuy' => 'RfqDetail',
        'addRfqServiceSell' => 'RfqDetail',
        'addRfqNote' => 'Rfq',

        // ADD PREORDER
        'addPreOrder' => 'PreOrder',

        // ADD FILE
        'addFile' => 'File',

        // UPDATE
        'updateUser' => 'User',
        'updateBranch' => 'Branch',
        'updateCountry' => 'Country',
        'updateCurrency' => 'Currency',
        'updateCity' => 'Port',
        'updateCompany' => 'Company',
        'updateContainerSize' => 'ContainerSize',
        'updateContainerType' => 'ContainerType',
        'updateDistrict' => 'District',
        'updateEmployee' => 'Employee',
        'updateEmployeeDisease' => 'EmployeeDisease',
        'updateMeasurementUnit' => 'MeasurementUnit',
        'updateMenu' => 'Menu',
        'updateNote' => 'Note',
        'updatePort' => 'Port',
        'updatePrincipal' => 'Principal',
        'updatePrincipalBankAccount' => 'PrincipalBankAccount',
        'updatePrincipalBlacklist' => 'PrincipalBlacklist',
        'updatePrincipalCommodity' => 'PrincipalCommodity',
        'updatePrincipalGroup' => 'PrincipalGroup',
        'updateService' => 'Service',
        'updateServiceGroup' => 'ServiceGroup',
        'updateServicePrice' => 'ServicePrice',
        'updateServiceTag' => 'ServiceTag',
        'updateServiceTerm' => 'ServiceTerm',
        'updateSetting' => 'Setting',
        'updateUserGroup' => 'UserGroup',
        'updateCarrier' => 'Carrier',
        'updateServiceBudget' => 'ServiceBudget',
        'updateBc' => 'Bc',
        'updateContainer' => 'Container',
        'updateDeliveryStatus' => 'DeliveryStatus',
        'updateTaxInvoice' => 'TaxInvoice',
        'updateCommodityCategory' => 'CommodityCategory',
        'updateLogo' => 'Logo',
        'updateNationalHoliday' => 'NationalHoliday',
        'updatePaymentMethod' => 'PaymentMethod',
        'updateOriginalCopy' => 'OriginalCopy',
        'updatePaymentTerm' => 'PaymentTerm',
        'updatePortInterchange' => 'PortInterchange',
        'updatePrincipalCategory' => 'PrincipalCategory',
        'updatePrincipalTitle' => 'PrincipalTitle',
        'updateRemark' => 'Remark',
        'updateReminder' => 'Reminder',
        'updateServiceCategory' => 'ServiceCategory',
        'updateDocumentSetting' => 'DocumentSetting',
        'updateDocumentDistribution' => 'DocumentDistribution',
        'updateWebsite' => 'Website',
        'updateUserTeam' => 'UserTeam',
        'updateUserTeamDetail' => 'UserTeamDetail',
        'updateBankAccount' => 'BankAccount',
        'updateTaxInvoiceDetail' => 'TaxInvoiceDetail',
        'updateTaxInvoiceVoid' => 'TaxInvoiceVoid',
        'updateNoteTemplate' => 'NoteTemplate',
        'updatePrincipalAddress' => 'PrincipalAddress',
        'updatePrincipalCategoryDetail' => 'PrincipalCategoryDetail',
        'updatePrincipalPic' => 'PrincipalPic',
        'updateContainerAgency' => 'ContainerAgency',
        'updateNotification' => 'Notification',
        'updateQuotation' => 'Rfq',
        'updateStatusQuotation' => 'Rfq',
        'updateTeamWork' => 'TeamWork',
        'updateRfqCargo' => 'RfqCargo',
        'updateRfqServiceBuy' => 'RfqDetail',
        'updateRfqServiceSell' => 'RfqDetail',
        'updateRfqNote' => 'Rfq',

        // UPDATE PREORDER
        'updatePreOrder' => 'PreOrder',        

        // SOFT DELETES
        'softDeleteUser' => 'User',
        'softDeleteBranch' => 'Branch',
        'softDeleteCountry' => 'Country',
        'softDeleteCurrency' => 'Currency',
        'softDeleteCity' => 'Port',
        'softDeleteCompany' => 'Company',
        'softDeleteContainerSize' => 'ContainerSize',
        'softDeleteContainerType' => 'ContainerType',
        'softDeleteDistrict' => 'District',
        'softDeleteEmployee' => 'Employee',
        'softDeleteEmployeeDisease' => 'EmployeeDisease',
        'softDeleteMeasurementUnit' => 'MeasurementUnit',
        'softDeleteMenu' => 'Menu',
        'softDeleteNote' => 'Note',
        'softDeletePort' => 'Port',
        'softDeletePrincipal' => 'Principal',
        'softDeletePrincipalBankAccount' => 'PrincipalBankAccount',
        'softDeletePrincipalBlacklist' => 'PrincipalBlacklist',
        'softDeletePrincipalCommodity' => 'PrincipalCommodity',
        'softDeletePrincipalGroup' => 'PrincipalGroup',
        'softDeleteService' => 'Service',
        'softDeleteServiceGroup' => 'ServiceGroup',
        'softDeleteServicePrice' => 'ServicePrice',
        'softDeleteServiceTag' => 'ServiceTag',
        'softDeleteServiceTerm' => 'ServiceTerm',
        'softDeleteSetting' => 'Setting',
        'softDeleteUserGroup' => 'UserGroup',
        'softDeleteCarrier' => 'Carrier',
        'softDeleteServiceBudget' => 'ServiceBudget',
        'softDeleteBc' => 'Bc',
        'softDeleteContainer' => 'Container',
        'softDeleteDeliveryStatus' => 'DeliveryStatus',
        'softDeleteTaxInvoice' => 'TaxInvoice',
        'softDeleteCommodityCategory' => 'CommodityCategory',
        'softDeleteLogo' => 'Logo',
        'softDeleteNationalHoliday' => 'NationalHoliday',
        'softDeletePaymentMethod' => 'PaymentMethod',
        'softDeleteOriginalCopy' => 'OriginalCopy',
        'softDeletePaymentTerm' => 'PaymentTerm',
        'softDeletePortInterchange' => 'PortInterchange',
        'softDeletePrincipalCategory' => 'PrincipalCategory',
        'softDeletePrincipalTitle' => 'PrincipalTitle',
        'softDeleteRemark' => 'Remark',
        'softDeleteReminder' => 'Reminder',
        'softDeleteServiceCategory' => 'ServiceCategory',
        'softDeleteDocumentSetting' => 'DocumentSetting',
        'softDeleteDocumentDistribution' => 'DocumentDistribution',
        'softDeleteWebsite' => 'Website',
        'softDeleteUserTeam' => 'UserTeam',
        'softDeleteUserTeamDetail' => 'UserTeamDetail',
        'softDeleteBankAccount' => 'BankAccount',
        'softDeleteTaxInvoiceDetail' => 'TaxInvoiceDetail',
        'softDeleteTaxInvoiceVoid' => 'TaxInvoiceVoid',
        'softDeleteNoteTemplate' => 'NoteTemplate',
        'softDeletePrincipalAddress' => 'PrincipalAddress',
        'softDeletePrincipalCategoryDetail' => 'PrincipalCategoryDetail',
        'softDeletePrincipalPic' => 'PrincipalPic',
        'softDeleteContainerAgency' => 'ContainerAgency',

        // DELETE PRE BOOKING
        'softDeleteLockedParty' => 'PrincipalBlacklist',
        'softDeleteQuotation' => 'Rfq',
        'softDeleteTeamWork' => 'TeamWork',
        'softDeleteRfqCargo' => 'RfqCargo',
        'softDeleteRfqServiceBuy' => 'RfqDetail',
        'softDeleteRfqServiceSell' => 'RfqDetail',
        'softDeleteRfqNote' => 'Rfq',


        // DELETE PREORDER
        'softDeletePreOrder' => 'PreOrder',

        // APPROVE / DISAPPROVE
        'approvePreOrder' => 'PreOrder',
        'disapprovePreOrder' => 'PreOrder',

        // DELETE FILE
        'softDeleteFile' => 'File',
    ];


    public function getActionsToModel()
    {
        return $this->actionsToModel;
    }
}
